---

- name: install pre-req
  apt:
    name:
      - opendjk-11-jdk
    state: latest

  when: ansible_distribution == "Ubuntu"

- name: add elasticsearch apt key
  apt_key:
    url: "https://packages.elastic.co/GPG-Key-elasticsearch"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: adding elastic repo
  apt_repository:
     repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
  when: ansible_distribution == "Ubuntu"

- name: install elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
    masked: no
  when: ansible_distribution == "Ubuntu"

- name: allow outside access elasticsearch (Ubuntu)
  apt:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: 0.0.0.0'
    state: present
  when: ansible_distribution == "ubuntu"

- name: enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes


